### ISSUE TITLE
Fixed SideBar (NavPage)?

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/UniformDocs#353]
As a regular user, I find it a little bit frustrating when I just want to navigate through different items and I'm not looking for something specific.

Gif:
![uniformdocs](https://user-images.githubusercontent.com/8951553/43911417-b008baf2-9bff-11e8-9e16-b203a312a5f8.gif)

**Comment by alshakero** [comment]
If I'm not wrong this is only acheivable if the sidebar has a max height of 100vh and has more. Or it should have scroll bars like this:
![image](https://user-images.githubusercontent.com/17054134/43911972-31827d9c-9c01-11e8-802c-e8d104f5848e.png)

Which I think looks strange.

**Comment by Mihaiii** [comment]
> Which I think looks strange.
It doesn't have to be there all the time. This is a nice example, IMO: https://semantic-ui.com/introduction/integrations.html .

Anyway, feel free to close it.

**Comment by alshakero** [comment]
> This is a nice example

I agree this is super lovely. Maybe we should have that in `uni-layout-left-nav`

/cc @tomalec @warpech

**Comment by alshakero** [comment]
How beautiful is this?

![scroll](https://user-images.githubusercontent.com/17054134/43916348-9e802438-9c0d-11e8-8075-0741fee511e3.gif)

The only downside is it needs a minor breaking change in the HTML required for the left-nav-layout. You need to wrap the right side with a div like this:

```html
<div class="uni-layout-right-content">
    <slot name="uniformdocs/current"></slot>
</div>
```

<details>
<summary>I acheived this by the following CSS</summary>

```css
/* Layout with left side navigation */

.uni-layout-left-nav {
  display: grid;
  background: var(
    --uni-layout-left-nav-background,
    var(--uni-default-layout-left-nav-background)
  );
  grid-template-columns: 200px 1fr;
  height: 100vh;
}
.uni-layout-right-content {
  height: 100vh;
  overflow: auto;
}

.uni-vertical-nav {
  background: var(
    --uni-vertical-nav-color,
    var(--uni-default-vertical-nav-color)
  );
  color: var(
    --uni-vertical-nav-contrast,
    var(--uni-default-vertical-nav-contrast)
  );
  padding: 20px 10px 20px 20px;
  height: 100vh;
  overflow: auto;
}

.uni-vertical-nav::-webkit-scrollbar {
  width: 10px;
}

.uni-vertical-nav::-webkit-scrollbar {
  -webkit-appearance: none;
}

.uni-vertical-nav::-webkit-scrollbar-track {
  background: var(
    --uni-vertical-nav-color,
    var(--uni-default-vertical-nav-color)
  );
  width: 10px;
  transition: all 0.2s linear;
}

.uni-vertical-nav:hover::-webkit-scrollbar-track {
  background-color: rgba(255,255,255,0.2);
}
.uni-vertical-nav:hover::-webkit-scrollbar-thumb {
  background-color: rgba(255,255,255,0.2)
}
```

</details>
